---
dependency:
  name: galaxy
driver:
  name: vagrant

platforms:
  - name: test-ansible-role-netflow-replicator
    box: ${TEST_PLATFORM_BOX:-debian/buster64}
    box_version: ${TEST_PLATFORM_BOX_VERSION:-""}
    config_options:
      synced_folder: no
    memory: 512
    cpus: 1

provisioner:
  name: ansible
  playbooks:
    verify: ../shared/${TEST_VERIFY_PLAYBOOK:-verify.yml}
verifier:
  name: ansible
